#!/bin/sh
# $Id: mkdist 149 2008-11-03 18:51:28Z dtrg $
# $HeadURL: https://wordgrinder.svn.sf.net/svnroot/wordgrinder/wordgrinder/mkdist $
# $LastChangedDate: 2007-10-05 00:12:15 +0100 (Fri, 05 Oct 2007) $
#
# Script to build a distribution package.

set -e

PACKAGE=olua
	
if [ "$1" = "" ]; then
	echo "Please specify a version number!"
	exit 1
fi

if [ -d ../$PACKAGE-$1 ]; then
	echo "I think you've already generated version $1."
	exit 1
fi

mkdir ../$PACKAGE-$1

tar cf - . --exclude="*/.*" --exclude="debian" --exclude="bin" \
	| (cd ../$PACKAGE-$1; tar xf -) 
rm ../$PACKAGE-$1/mkdist

(cd .. && tar cvf $PACKAGE-$1.tar.bz2 --bzip2 $PACKAGE-$1)

echo ""
echo "Done --- but did you remember to update the version number in the README?"

